// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw7O7tj-UIcipX29JQD_LZNgVrj8Dd-IY',
    appId: '1:331945452704:web:581be66cf94fd168c815c5',
    messagingSenderId: '331945452704',
    projectId: 'ar-furniture-app-f5fb3',
    authDomain: 'ar-furniture-app-f5fb3.firebaseapp.com',
    storageBucket: 'ar-furniture-app-f5fb3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrVq3V4iToK6jvVXpuqqxEerGxIOUJtW4',
    appId: '1:331945452704:android:5035ce560615f0eec815c5',
    messagingSenderId: '331945452704',
    projectId: 'ar-furniture-app-f5fb3',
    storageBucket: 'ar-furniture-app-f5fb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDqbluVdn7p8oD0LLoYRaxabGM3bxApGw',
    appId: '1:331945452704:ios:5cc0fb690dc90c07c815c5',
    messagingSenderId: '331945452704',
    projectId: 'ar-furniture-app-f5fb3',
    storageBucket: 'ar-furniture-app-f5fb3.appspot.com',
    iosBundleId: 'com.example.arFurnitureApp',
  );
}
